In [246]:
import pandas as pd

In [247]:
df = pd.read_csv('customer_shopping_behavior.csv')

In [248]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [249]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [250]:
df.describe(include = 'all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [251]:
# Checking the null values
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [252]:
# Replacing null values of each category with their median values
df['Review Rating'] = df.groupby(['Category'])['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [253]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [254]:
# Checking unique values of each column to see if there is any inconsistent formatting issue
for col in df.columns:
    print(df[col].unique())
    print('='*30)

[   1    2    3 ... 3898 3899 3900]
==============================
[55 19 50 21 45 46 63 27 26 57 53 30 61 65 64 25 52 66 31 56 18 38 54 33
 36 35 29 70 69 67 20 39 42 68 49 59 47 40 41 48 22 24 44 37 58 32 62 51
 28 43 34 23 60]
==============================
<StringArray>
['Male', 'Female']
Length: 2, dtype: str
==============================
<StringArray>
[    'Blouse',    'Sweater',      'Jeans',    'Sandals',   'Sneakers',
      'Shirt',     'Shorts',       'Coat',    'Handbag',      'Shoes',
      'Dress',      'Skirt', 'Sunglasses',      'Pants',     'Jacket',
     'Hoodie',    'Jewelry',    'T-shirt',      'Scarf',        'Hat',
      'Socks',   'Backpack',       'Belt',      'Boots',     'Gloves']
Length: 25, dtype: str
==============================
<StringArray>
['Clothing', 'Footwear', 'Outerwear', 'Accessories']
Length: 4, dtype: str
==============================
[ 53  64  73  90  49  20  85  34  97  31  68  72  51  81  36  38  48  62
  37  88  22  25  56  94  79  67  91  33  69  45  60  76  39 100  21  43
  54  55  30  28  59  24  83  46  70  29  26  58  96  40  32  95  41  47
  99  87  92  98  89  35  75  65  86  84  77  27  23  74  80  42  61  82
  78  93  50  57  66  44  52  71  63]
==============================
<StringArray>
[      'Kentucky',          'Maine',  'Massachusetts',   'Rhode Island',
         'Oregon',        'Wyoming',        'Montana',      'Louisiana',
  'West Virginia',       'Missouri',       'Arkansas',         'Hawaii',
       'Delaware',  'New Hampshire',       'New York',        'Alabama',
    'Mississippi', 'North Carolina',     'California',       'Oklahoma',
        'Florida',          'Texas',         'Nevada',         'Kansas',
       'Colorado',   'North Dakota',       'Illinois',        'Indiana',
        'Arizona',         'Alaska',      'Tennessee',           'Ohio',
     'New Jersey',       'Maryland',        'Vermont',     'New Mexico',
 'South Carolina',          'Idaho',   'Pennsylvania',    'Connecticut',
           'Utah',       'Virginia',        'Georgia',       'Nebraska',
           'Iowa',   'South Dakota',      'Minnesota',     'Washington',
      'Wisconsin',       'Michigan']
Length: 50, dtype: str
==============================
<StringArray>
['L', 'S', 'M', 'XL']
Length: 4, dtype: str
==============================
<StringArray>
[     'Gray',    'Maroon', 'Turquoise',     'White',  'Charcoal',    'Silver',
      'Pink',    'Purple',     'Olive',      'Gold',    'Violet',      'Teal',
  'Lavender',     'Black',     'Green',     'Peach',       'Red',      'Cyan',
     'Brown',     'Beige',    'Orange',    'Indigo',    'Yellow',   'Magenta',
      'Blue']
Length: 25, dtype: str
==============================
<StringArray>
['Winter', 'Spring', 'Summer', 'Fall']
Length: 4, dtype: str
==============================
[3.1 3.5 2.7 2.9 3.2 2.6 4.8 4.1 4.9 4.5 4.7 2.8 4.6 3.3 4.4 3.6 5.  4.
 3.7 4.2 3.9 3.  3.8 3.4 4.3 2.5]
==============================
<StringArray>
['Yes', 'No']
Length: 2, dtype: str
==============================
<StringArray>
[       'Express',  'Free Shipping',   'Next Day Air',       'Standard',
 '2-Day Shipping',   'Store Pickup']
Length: 6, dtype: str
==============================
<StringArray>
['Yes', 'No']
Length: 2, dtype: str
==============================
<StringArray>
['Yes', 'No']
Length: 2, dtype: str
==============================
[14  2 23 49 31 19  8  4 26 10 37 34 44 36 17 46 50 22 32 40 16 13  7 41
 45 38 48 18 15 25 39 35 29 21 43  3  5 24 42 47 28 20 33  1  9 12 27 11
 30  6]
==============================
<StringArray>
['Venmo', 'Cash', 'Credit Card', 'PayPal', 'Bank Transfer', 'Debit Card']
Length: 6, dtype: str
==============================
<StringArray>
[   'Fortnightly',         'Weekly',       'Annually',      'Quarterly',
      'Bi-Weekly',        'Monthly', 'Every 3 Months']
Length: 7, dtype: str
==============================

In [255]:
df['Frequency of Purchases'] = df['Frequency of Purchases'].replace({'Fortnightly': 'Bi-Weekly','Every 3 Months':'Quarterly'})

In [256]:
df['Frequency of Purchases'].unique()

<StringArray>
['Bi-Weekly', 'Weekly', 'Annually', 'Quarterly', 'Monthly']
Length: 5, dtype: str

In [257]:
# To check duplicate values
df['Customer ID'].value_counts().unique()

array([1])

In [258]:
# To rename column names in snake case
df.columns = df.columns.str.lower().str.replace(' ','_')
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [259]:
df = df.rename(columns = {'purchase_amount_(usd)' :'purchase_amount'})

In [260]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [261]:
# Making a new column Age group to do age group wise analysis later
def age_grp(x):
    if x < 25:
        y = 'young_adult'
    elif 25 <= x < 35:
        y = 'adult'
    elif 35 <= x < 50:
        y = 'middle_aged'
    else:
        y = 'senior'

    return y

In [262]:
df['age_group'] = df['age'].apply(age_grp)

In [263]:
df[['age','age_group']].head(10)

   age    age_group
0   55       senior
1   19  young_adult
2   50       senior
3   21  young_adult
4   45  middle_aged
5   46  middle_aged
6   63       senior
7   27        adult
8   26        adult
9   57       senior

In [264]:
# Mapping purchase frequency in numeric values
df['purchase_freq_in_days'] = df['frequency_of_purchases'].map(
    {
     'Weekly': 7,
     'Annually': 365,
     'Quarterly': 90,
     'Bi-Weekly': 14,
     'Monthly': 30}
)

df['purchase_freq_in_days'].unique()

array([ 14,   7, 365,  90,  30])

In [265]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_freq_in_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Bi-Weekly,senior,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Bi-Weekly,young_adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,senior,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly,young_adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually,middle_aged,365

In [266]:
# Checking if columns 'discount_applied' and 'promo_code_used' are giving exact same information. then one of the column will be redundant

df[df['discount_applied'] != df['promo_code_used']]

Empty DataFrame
Columns: [customer_id, age, gender, item_purchased, category, purchase_amount, location, size, color, season, review_rating, subscription_status, shipping_type, discount_applied, promo_code_used, previous_purchases, payment_method, frequency_of_purchases, age_group, purchase_freq_in_days]
Index: []

In [267]:
# Both the columns are exactly same. We can drop promo_code_used

df.drop('promo_code_used', axis = 1)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_freq_in_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Bi-Weekly,senior,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Bi-Weekly,young_adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,senior,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,young_adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,middle_aged,365
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,32,Venmo,Weekly,middle_aged,7
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,41,Bank Transfer,Bi-Weekly,senior,14
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,24,Venmo,Quarterly,middle_aged,90
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,24,Venmo,Weekly,middle_aged,7
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,33,Venmo,Quarterly,senior,90

In [268]:
import urllib.parse
from sqlalchemy import create_engine

# Database settings
host = r'localhost\SQLEXPRESS'
database = 'customer_behaviour'

# Build connection string for Windows Authentication
connection_string = (
    f"DRIVER={{ODBC Driver 17 for SQL Server}};"
    f"SERVER={host};"
    f"DATABASE={database};"
    f"Trusted_Connection=yes;"
)

params = urllib.parse.quote_plus(connection_string)
engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

# Write DataFrame to SQL Server
df.to_sql("customer", engine, if_exists="replace", index=False)

52